server:
  port: 8090

spring:
  application:
    name: Kafka Elastic
    title: Kafka Elastic
    version: 1.0.0-SNAPSHOT
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        readMessage-in-0:
          destination: hero
          group: spring-boot-kafka
          consumer:
            concurrency: 3
#            properties.spring.json.trusted.packages: org.springframework.*,info.antoniomartin.kafka.models.Hero
          batch-mode: true
      kafka:
        binder:
          brokers: kafka:9092
          replication-factor: 1
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            spring.json.trusted.packages: '*'
            spring.json.use.type.headers: true
          configuration:
            commit.interval.ms: 1000
            cache.max.bytes.buffering: 1049000
            isolation.level: read_committed
            producer.acks: all
            spring.json.add.type.headers: true

logging.level.org.springframework.kafka: INFO
